### ISSUE TITLE
参数问题和感谢

### ISSUE THREAD

**Issue by zhongyikeshu** [wiwjp/ABD-Net#38]
您好大佬，我想请教一下您。您的README_Training_and_Testing_Guides.md 给出的参数是论文中在market-1501数据集上获得最优结果时使用的参数嘛？我只得到了95.3%的rank1而论文中是95.6%，在怀疑是不是参数的问题。感谢您的帮助，您的代码十分优雅，小弟非常喜欢，叹为观止！

**Comment by code10086web** [comment]
Hi,Could you told me the parameter of rank1-95.3%? thank you very much! I only obtained 94.3%.

**Comment by code10086web** [comment]
> 您好大佬，我想请教一下您。您的README_Training_and_Testing_Guides.md 给出的参数是论文中在market-1501数据集上获得最优结果时使用的参数嘛？我只得到了95.3%的rank1而论文中是95.6%，在怀疑是不是参数的问题。感谢您的帮助，您的代码十分优雅，小弟非常喜欢，叹为观止！

Hi, Could you told me the parameter of rank1-95.3%? thank you very much! I only obtained 94.3%.

**Comment by zhongyikeshu** [comment]
> 
> 
> > 您好大佬，我想请教一下您。您的README_Training_and_Testing_Guides.md 给出的参数是论文中在market-1501数据集上获得最优结果时使用的参数嘛？我只得到了95.3%的rank1而论文中是95.6%，在怀疑是不是参数的问题。感谢您的帮助，您的代码十分优雅，小弟非常喜欢，叹为观止！
> 
> Hi, Could you told me the parameter of rank1-95.3%? thank you very much! I only obtained 94.3%.

**Comment by zhongyikeshu** [comment]
抱歉刚看到，，，我基本上就是完全使用的ABD-Net github上使用了默认参数。。。不知道为啥能差别这么大。。。。我是菜鸡哈哈哈哈很多都不懂



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VITA-Group/ABD-Net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上8:10
收件人:&nbsp;"VITA-Group/ABD-Net"<ABD-Net@noreply.github.com&gt;;
抄送:&nbsp;"1142571013"<1142571013@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [VITA-Group/ABD-Net] 参数问题和感谢 (#38)





  
您好大佬，我想请教一下您。您的README_Training_and_Testing_Guides.md 给出的参数是论文中在market-1501数据集上获得最优结果时使用的参数嘛？我只得到了95.3%的rank1而论文中是95.6%，在怀疑是不是参数的问题。感谢您的帮助，您的代码十分优雅，小弟非常喜欢，叹为观止！
  
Hi, Could you told me the parameter of rank1-95.3%? thank you very much! I only obtained 94.3%.
